require("config.options")
require("config.autocommands")
require("config.lazy")
require("config.keymaps")
require("config.set-theme")
require("config.require-setups")
require("config.lualine-config")
